# Key to use when accessing flask app config
DATABASE_CONFIG_KEY = "DB"
METRICS_CONFIG_KEY = "METRICS"
USERS_CONFIG_KEY = "USERS"

# Session key names
SESSION_USER_ID_KEY = "user_id"
SESSION_USER_EMAIL_KEY = "user_email"
SESSION_USER_NAME_KEY = "user_name"

# Cache
REDIS_VERSION = 6
PRODUCT_DISPLAY_NAME_CACHE_PREFIX = "pdn_"
PRODUCT_PRICE_HISTORY_CACHE_PREFIX = "pph_"
PRODUCT_SEARCH_CACHE_PREFIX = "ps_"
CATEGORY_PRODUCTS_CACHE_KEY = "cpd_"
CATEGORIES_CACHE_KEY = "categories"

DATE_FORMAT_STRING = "%Y-%m-%d"

MAX_METRICS_SIZE = 1048576
MAX_METRICS_DOCUMENTS = 100

ONE_DAY_IN_SECONDS = 24 * 60 * 60
